# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

networks:
  main:
    name: itu-minitwit-network

services:
  minitwit:
    build:
      context: .
      dockerfile: Dockerfile-minitwit
      target: final
    networks:
      - main
    ports:
      - 5035:8080
    volumes:
      - ./data:/app/data
    environment:
      - DbPath=/app/data/minitwit.db
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-tests
    networks:
      - main
    depends_on:
      - minitwit
    environment:
      - BaseUrl=http://minitwit:8080

  apitests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-api-tests
    networks:
      - main
    depends_on:
      - minitwit
    environment:
      - BaseUrl=http://minitwit:8080/api
