services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit_container
    ports:
      - 5035:8080
    volumes:
      - ../data:/app/data
    environment:
      - DbPath=/app/data/minitwit.db
