services:
  dbserver:
    image: your_id/dbserver
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - minitwit-network

  webserver:
    image: your_id/webserver
    depends_on:
      dbserver:
        condition: service_healthy
    ports:
      - "5001:5000" # Depending on the OS using port 5000 might be reserved. If not, change to "5000:5000" or something similar.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
        - minitwit-network

  clidownload:
    image: appropriate/curl
    depends_on:
      webserver:
        condition: service_healthy
    networks:
      - minitwit-network
    entrypoint: sh -c  "curl http://webserver:5000" # If above applies remember to change this as well.

networks:
  minitwit-network:
    name: "minitwit-network"
    external: True